# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f40935197376d132132f8974d85ad6a2d4d507e22b6788d3b58fc7b9057bd217f2d61cf910a1572971ced97dd57e033a12f5360623548ce813d335eec372a257

test:
  secret_key_base: ddbbab8d7fc3886a145abe05bfd2038f77fefdbe54d409b7a7a3389b7e21249e813389b674995f87c57180dfd5682d2b8ec192338170c7b01775c1edd3baf33e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
